name: dataengineering
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - mlflow=2.6.0
  - scikit-learn=1.3.0
  - pandas=2.0.3
  - seaborn=0.12.2
  - psycopg2=2.9.3
  - pip=23.1.2
  - pip:
    - hydra-core==1.3.2
    - s3fs==2023.6.0
    - boto3